### PR TITLE
Convert highcharts tests to use react-testing-library

### PR DESCRIPTION
**Pull request by anajavi**
Replaces enzyme with react-testing-library and react-test-renderer/shallow.

Also upgrades to react v17.

### CODE REVIEW

**Comment by whawker** [comment]
This is really nice work.

Apologies for neglecting this project as of late. My free time to devote time to this project has dwindled down to basically zero mainly due to lockdown here in the UK. For that I'm very sorry. I greatly appreciate your contributions in my absence.

**Review by whawker — APPROVED** [review]

**Comment by anajavi** [comment]
> This is really nice work.
> 
> Apologies for neglecting this project as of late. My free time to devote time to this project has dwindled down to basically zero mainly due to lockdown here in the UK. For that I'm very sorry. I greatly appreciate your contributions in my absence.

No worries. Besides, changing unit tests aren't the most urgent thing anyway :)

I can do the release if you don't mind?

**Comment by whawker** [comment]
That would be fantastic, thanks @anajavi

**Comment by anajavi** [comment]
I'll do a release a bit later this weekend then.

**Pull request merged**
