### PR TITLE
WIP: Highcharts v7 support

### PR DESCRIPTION
**Pull request by anajavi**
Changelog: https://www.highcharts.com/documentation/changelog

New series types
- [X] [networkgraph](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/network-graph/)
- [X] [packedbubble](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/packed-bubble/)
- [X] [cylinder](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/cylinder/)
- [X] [venn](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/venn-diagram/)
- [X] [columnpyramid](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-pyramid/) - Changelog says pyramid, but we already have that. So I think they must mean Column Pyramid?

Styled mode
- [X] Explore options for the new [chart.styledMode](https://api.highcharts.com/highcharts/chart.styledMode) option

Documentation
- [X] Update version on README

### CODE REVIEW

**Comment by anajavi** [comment]
I tried to do just:

**Comment by anajavi** [comment]
This works for styledMode, but is not the most elegant solution:
```jsx
<HighchartsChart chart={ { styledMode:true }}>
```

Doing it via update leads to mixed results, the Highcharts root svg element gets font-family attribute.
```jsx
<HighchartsChart>
        <Chart styledMode={true} />
```

Should we just add styledMode prop to HighchartsChart? Like this:
```jsx
<HighchartsChart styledMode={true} />
```
I see no easy way of setting styledMode in Chart.

**Comment by whawker** [comment]
The [commit](https://github.com/whawker/react-jsx-highcharts/pull/194/commits/099d5d6a6226b6256898644d51ec1cd367fdf1f0) I've just pushed should resolve that

**Comment by whawker** [comment]
@anajavi just published `react-jsx-highcharts@3.4.0-alpha.2` if you wanted to do some testing?

**Comment by anajavi** [comment]
I fell ill, I'll try to do testing tomorrow.

Great work!

**Comment by whawker** [comment]
Oh no! Get well soon mate!

**Comment by anajavi** [comment]
I tried to make example of PackedBubbleSeries, but it doesn't render anything. I don't know if I'm doing something wrong.
```jsx
const europeData = [
  {
    name: 'Germany',
    value: 767.1
  },
  {
    name: 'Croatia',
    value: 20.7
  },
  {
    name: 'Belgium',
    value: 97.2
  }
];
const plotOptions = {
  packedbubble: {
    dataLabels: {
      enabled: true,
      format: '{point.name}',
      filter: {
        property: 'y',
        operator: '>',
        value: 250
      },
      style: {
        color: 'black',
        textOutline: 'none',
        fontWeight: 'normal'
      }
    },
    minPointSize: 5
  }
};
const App = () => {
  return (
    <div className="app">
      <HighchartsChart plotOptions={plotOptions}>
        <Chart />
        <Title>Highcharts PackedBubble Diagram</Title>

        <PackedBubbleSeries name="Europe" data={europeData} />

        <Tooltip />
      </HighchartsChart>
```

I did not try NetworkGraph and CylinderSeries.

Everything else seems to work okay.

**Comment by anajavi** [comment]
Shouldn't the PackedBubbleSeries be in index.js as:
```javascript
export const PackedBubbleSeries = withSeriesType('PackedBubble', axisNotRequired);
```

It doesn't need axis.

**Comment by whawker** [comment]
Ah yes, you're right. [Vanilla Highcharts](https://jsfiddle.net/63bLaxge/)

**Comment by anajavi** [comment]
Probably the same for networkgraph? Not sure about cylinder though, the vanilla example does not have axis, but it might use it if provided?

**Comment by anajavi** [comment]
LGTM.

I think it is good to go.

**Comment by whawker** [comment]
Just published everything. https://github.com/whawker/react-jsx-highcharts/releases/tag/v3.4.0

Thanks again for all your hard work @anajavi!

**Comment by anajavi** [comment]
Thank you!

I think the Annotation component should be mentioned in the release notes too?

**Comment by whawker** [comment]
Good spot

**Pull request merged**
