### PR TITLE
Support react 18

### PR DESCRIPTION
**Pull request by anajavi**
- Allow react 18 as peer dependency
- Run tests against react 18

This still needs #332 to not crash when using StrictMode.

### CODE REVIEW

**Review by whawker — APPROVED** [review]

**Comment by anajavi** [comment]
@whawker should I release this as v4.4.0?

**Comment by anajavi** [comment]
> @whawker should I release this as v4.4.0?

Or maybe 5.0.0-alpha.0?

**Comment by whawker** [comment]
New major makes sense to me

**Comment by anajavi** [comment]
> New major makes sense to me

Okay. I'll release it then.

**Pull request merged**
