### PR TITLE
Add Highcharts 7.1 support

### PR DESCRIPTION
**Pull request by whawker**
Also fixes a few outstanding bugs.

Most notably #209, where we now use `requestAnimationFrame` for debouncing chart redraws, (instead of lodash `debounce`). 

This is necessary as Highcharts [destroys axes when they are updated](https://github.com/highcharts/highcharts/blob/master/js/parts/Dynamics.js#L1130), so we need to redraw it by the next animation frame, otherwise we see the white flash.

This seems to be the best compromise between limiting unnecessary redraws, and prevent white flashes.

### CODE REVIEW

**Comment by whawker** [comment]
Thinking I will gitignore the `bundle.js` and `index.html` example files on the master branch, but keep them on the gh-pages branch. Seems no value in having them on master.

**Comment by anajavi** [comment]
I like the idea of using requestAnimationFrame instead of setTimeout.

The code looks fine to me, but I'd like to check how it behaves in profiler. Hopefully by tomorrow.

If you are preparing for a release I could also update some dependencies. Notably switching from create-react-context to https://github.com/StringEpsilon/mini-create-react-context which is used by react-router nowadays

**Comment by whawker** [comment]
Sounds like a good idea. Yep, I'm looking to push out a release soon - have been neglecting this project recently, but I don't want people to think it's dead!

**Comment by anajavi** [comment]
Quick profiling did not reveal anything special, so I say it is good to go.

Great work!

**Pull request merged**
