### PR TITLE
Upgrade to babel 7

### PR DESCRIPTION
**Pull request by anajavi**
This PR updates all packages to build with babel 7.

Benefits:
- es2018 support
- JSX Fragment Support (<>)
- smaller bundles

This also sets the  transform-runtime to not to do polyfilling. If you know that there are polyfills needed it can be turned back on.

Also updates a couple of dependencies.

Again, the react-jsx-highcharts package has seen much more testing than the others.

### CODE REVIEW

**Comment by whawker** [comment]
Looks good to me @anajavi. Would you be interested in joining me as a project maintainer?

**Comment by anajavi** [comment]
What does project maintainer do?

**Comment by whawker** [comment]
It would basically give you [these permissions](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account), basically it would allow you to make changes to the project without requiring me to approve everything?

**Comment by anajavi** [comment]
That sounds nice.

A couple of things I'd like to do:
- use default eslint config instead of create-react-app
- add CI server like circleci to automatically lint & run tests on every commit

**Comment by whawker** [comment]
I have created #159 to discuss this.

**Pull request merged**
