### PR TITLE
drop lodash-es dependency from react-jsx-highcharts

### PR DESCRIPTION
**Pull request by anajavi**
### what?

This replaces ```attempt(...)``` calls with ```try {...} catch { // ignore }```

### why?

It allows us to drop lodash-es dependency from react-jsx-highcharts, other libs still use some lodash functions.

This reduces bundle size by some 1kB.

### CODE REVIEW

**Comment by whawker** [comment]
Looks good, although I think we need to remove the `LodashWebpackPlugin` from [`webpack.config.js`](https://github.com/whawker/react-jsx-highcharts/blob/0689aebecea2cf36150b258fbfd722010d334e22/packages/react-jsx-highcharts/webpack.config.js#L3)?

Would you mind removing `lodash-es` from the Highstock/Highmaps `package.json`s too?

**Comment by anajavi** [comment]
> Looks good, although I think we need to remove the `LodashWebpackPlugin` from [`webpack.config.js`](https://github.com/whawker/react-jsx-highcharts/blob/0689aebecea2cf36150b258fbfd722010d334e22/packages/react-jsx-highcharts/webpack.config.js#L3)?

It is removed from  webpack.config.js

> Would you mind removing `lodash-es` from the Highstock/Highmaps `package.json`s too?

Highstock and Highmaps still have a couple of imports from lodash-es, so they need some extra work still. Maybe we merge this and remove them in a separate PR?

**Comment by whawker** [comment]
> It is removed from webpack.config.js

🤦 my apologies

> Highstock and Highmaps still have a couple of imports from lodash-es, so they need some extra work still. Maybe we merge this and remove them in a separate PR?

I clearly haven't woken up this morning, good spot

**Review by whawker — APPROVED** [review]

**Comment by whawker** [comment]
I'll push out a new release

**Pull request merged**
