### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by anajavi**
### what?
This adds typescript definition for the library. Not complete, but all series types should have types.

References highcharts types.

Somewhat related to discussion in #113 and in https://github.com/whawker/react-jsx-highcharts/issues/267#issuecomment-578111704

### why?
- Better IDE experience even when writing plain js. 
- Type checking for those who use typescript

### caveats

- Event handlers are not typed, instead the evented components accept any props in addition to highcharts options

I am no way expert in writing definition files. I suggest that we release this and see what happens? It's easy to remove if it causes too much a headache. Maybe adding something in the release notes about "beta types".

### CODE REVIEW

**Comment by veloek** [comment]
We've been maintaining our own typings for (a subset of) RJH, so this is really great!

You haven't considered moving the codebase towards typescript? I realise it's quite some work to get there, but I think it would be worth while. If not, please make sure to keep the typings up-to-date. Misleading types are worse than no types.

**Comment by anajavi** [comment]
> We've been maintaining our own typings for (a subset of) RJH, so this is really great!

Can you please paste this definition to your module declaration and report if it works for you?

> You haven't considered moving the codebase towards typescript? I realise it's quite some work to get there, but I think it would be worth while.

That's up to whawker to decide. Previously typescript was quite cumbersome to use with react, but latest releases have been better. It's however quite an effort and adds complexity.

**Comment by veloek** [comment]
> Can you please paste this definition to your module declaration and report if it works for you?

We're using the react-jsx-highstock package and the highstock specific components are missing, but other than that it seems to work. There are a few `any` types though, which could be improved on further.

**Comment by anajavi** [comment]
> There are a few `any` types though, which could be improved on further.

Do you happen to have definitions for those?

**Comment by veloek** [comment]
Well, I would have to go through the components and look at the code. One simple example is `Credits` where the props type should be `{enabled: boolean}`.

**Comment by anajavi** [comment]
> Well, I would have to go through the components and look at the code. One simple example is `Credits` where the props type should be `Highcharts.CreditsOptions & { enabled?: boolean }`.

I added type for ```<Credits />``` in 19a4c688e9ee87a0b9852bebcab3c53e769deef6

**Comment by veloek** [comment]
Nice @anajavi, this is looking good! I would like to have the event handlers listed out though, instead of `[x: string]: any`, so they also get their appropriate types.

**Comment by anajavi** [comment]
> Nice @anajavi, this is looking good! I would like to have the event handlers listed out though, instead of `[x: string]: any`, so they also get their appropriate types.

Something like this should probably work:
```ts
  type ChartProps = {
    onSelection?: Highcharts.ChartSelectionCallbackFunction;
    [x: string]: any; // TODO: this is here to allow eventhandlers like onAfterAddSeries
  } & Partial<Highcharts.ChartOptions>;

  export function Chart(props: ChartProps): ReactElement;
```

There are however more events in highcharts than there are in their typings. One example is ```afterAddSeries```.

**Comment by anajavi** [comment]
> Nice @anajavi, this is looking good! I would like to have the event handlers listed out though, instead of `[x: string]: any`, so they also get their appropriate types.

@veloek I added the event handler typings if you like to try.

**Comment by whawker** [comment]
> You haven't considered moving the codebase towards typescript?

To be honest I don't know Typescript, so I would struggle to maintain the project. It is something I intend to learn but I don't use it day-to-day currently, like I do with JS

> I suggest that we release this and see what happens?

Worth releasing as a beta first?

**Comment by anajavi** [comment]
> Worth releasing as a beta first?

This certainly won't break anybodys application, but might confuse a bit. Maybe a beta release and mention in the #259 might get some feedback?

I intend to add some kind of test or eslint configuration for this later so we see if new highcharts release breaks the typings(most likely the eventhandlers).

**Review by whawker — APPROVED** [review]

**Comment by whawker** [comment]
Apologies for the insane delay on this, life during Covid just ends up trying to keep way too many balls in the air at once.

I've published a beta `react-jsx-highcharts@4.2.0-beta.1` containing the types added here.

Would those of you interested (@anajavi, @veloek) mind giving them a whirl?

**Comment by anajavi** [comment]
Works nicely at my end.

**Pull request merged**
