### PR TITLE
Replace useDelayOnce with simple useEffect

### PR DESCRIPTION
**Pull request by anajavi**
This removes useDelayOnce. Now the code depends on React doing useEffect calls in the order the Components are declared in JSX.

After this it is not possible to reference axis or series before they are rendered in document:
```jsx
<LineSeries axisId="myAxis" /><!-- does not work -->
<YAxis id="myAxis"/>
```

Now the code does not depend on timing of renders, which can change when concurrent mode lands in react.

Also this adds the same logic to coloraxis.

### CODE REVIEW

**Comment by anajavi** [comment]
This is the last breaking change I have in my mind. I hope after this we can wrap things up and release final version?

**Comment by whawker** [comment]
Looks good to me! Sorry for the delay!

**Comment by whawker** [comment]
@anajavi I think we're ready to release too, I will do it tomorrow though (16th) if thats ok.

**Comment by anajavi** [comment]
@whawker great! In the end it is the only way to uncover the real bugs :)

**Pull request merged**
